#!/usr/bin/env python3
"""Regenerate the static blog from trinity's own posts.ts, unattended.

The chain that publishes a blog post had a manual link in the middle. `blog/` is
generated by build-blog.py from `blog-posts.json`, and `blog-posts.json` was a
snapshot somebody refreshed by hand. verify-site.sh compares the slugs in the
shipped `Blog-*.js` chunk against `ls -d blog/*/` and fails on drift — correctly,
because a post the app lists and the static tree lacks is a 404 for every reader
who does not run JavaScript.

The consequence was that adding a post blocked its own publication, and with it
everything merged afterwards: from 2026-08-13 15:xx UTC to 2026-08-14, twelve
consecutive publisher runs failed on that gate and six unrelated merged pull
requests never reached a reader. The gate was right; nothing was wired to
satisfy it.

So this script owns the whole chain and the publisher calls it on every run:

    posts.ts  ->  blog-posts.json  ->  blog/ + ru/blog/ + feed.xml
                                   ->  og-blog-<slug>.svg/.png for new posts
                                   ->  sitemap.xml (build-landing.py)

Two deliberate choices:

* `publishedPosts` is a function, not an array. `JSON.stringify` on the binding
  itself returns `undefined` and writes a syntactically valid, entirely empty
  file without erroring — which would delete the blog rather than fail. Hence
  the call, and hence the assertions on the parsed result before anything is
  overwritten.

* The OG card is emitted from one layout table, not two renderers. Cards used to
  be hand-written SVG, rasterised on a Mac by qlmanage, which no runner has. A
  second, independent PNG path would drift from the SVG the first time either
  changed, so the layout lives in `card_layout()` and both writers consume it.
  Pillow draws with DejaVu, the only font family present on the runner that
  covers Cyrillic; the shipped cards were set in Inter, so an auto-generated
  card is recognisably not a hand-made one. That is a visible difference, not a
  hidden one.

Usage: python3 regen-blog.py [path-to-trinity/apps/website]
"""
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent
DATA = REPO / "blog-posts.json"
W, H = 1200, 630

FONT_DIRS = [
    "/usr/share/fonts/truetype/dejavu",
    "/usr/share/fonts/TTF",
    "/usr/share/fonts",
]


def font_path(bold: bool) -> str:
    name = "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf"
    for d in FONT_DIRS:
        p = Path(d) / name
        if p.is_file():
            return str(p)
    for d in FONT_DIRS:
        hits = sorted(Path(d).rglob(name)) if Path(d).is_dir() else []
        if hits:
            return str(hits[0])
    raise SystemExit(f"regen-blog: no {name} on this machine — cannot draw a card")


def run(cmd, cwd=None):
    r = subprocess.run(cmd, cwd=cwd, text=True, capture_output=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit(f"regen-blog: {' '.join(cmd[:3])} failed ({r.returncode})")
    return r.stdout


def extract(site: Path) -> list:
    """posts.ts -> parsed list, by transpiling the real module."""
    esbuild = site / "node_modules/.bin/esbuild"
    exe = [str(esbuild)] if esbuild.is_file() else ["npx", "--yes", "esbuild"]
    mjs = Path("/tmp/regen-posts.mjs")
    run(exe + ["src/data/blog/posts.ts", "--format=esm", "--platform=node",
               f"--outfile={mjs}", "--log-level=error"], cwd=site)
    out = run(["node", "-e",
               f"import('{mjs}').then(m=>"
               "process.stdout.write(JSON.stringify(m.publishedPosts(),null,1)))"])
    posts = json.loads(out)
    # Empty or malformed here would silently erase the blog on the next step,
    # which is a worse failure than not publishing.
    if not isinstance(posts, list) or len(posts) < 1:
        raise SystemExit(f"regen-blog: publishedPosts() gave {type(posts).__name__} "
                         f"of length {len(posts) if hasattr(posts,'__len__') else '?'}")
    for p in posts:
        for k in ("slug", "title", "summary", "date", "body"):
            if not p.get(k):
                raise SystemExit(f"regen-blog: post {p.get('slug','?')} has no {k}")
    return posts


def wrap(text: str, width: int, lines: int) -> list:
    words, out, cur = text.split(), [], ""
    for w in words:
        cand = f"{cur} {w}".strip()
        if len(cand) <= width or not cur:
            cur = cand
        else:
            out.append(cur)
            cur = w
            if len(out) == lines:
                break
    if cur and len(out) < lines:
        out.append(cur)
    if len(out) == lines and len(" ".join(out)) < len(text):
        out[-1] = out[-1].rstrip(" .,;:") + "…"
    return out


def card_layout(post: dict, lang: str) -> list:
    """One layout table, consumed by both writers.

    Each row is (x, y, size, bold, colour, text). The three statistics are the
    only numbers on the card and each is a count of something in the post
    itself, so a card cannot claim more than the article does.
    """
    t = post.get("ru", {}) if lang == "ru" else post
    title = t.get("title") or post["title"]
    summary = t.get("summary") or post["summary"]
    stats = (
        [(str(post.get("readingMinutes") or "—"), "мин чтения"),
         (str(len(post.get("receipts") or [])), "пруфов со ссылкой"),
         (str(len(post.get("openQuestions") or [])), "открытых вопросов")]
        if lang == "ru" else
        [(str(post.get("readingMinutes") or "—"), "minute read"),
         (str(len(post.get("receipts") or [])), "linked receipts"),
         (str(len(post.get("openQuestions") or [])), "open questions")]
    )
    rows = [(80, 132, 22, False, "#00ff88", "T27.AI · BLOG")]
    # Three lines at 46px, not two at 52: a two-line box truncated the longest
    # Russian titles mid-clause, and a card that ends in an ellipsis on the word
    # before the point advertises nothing.
    for i, line in enumerate(wrap(title, 34, 3)):
        rows.append((80, 212 + i * 56, 46, True, "#f2f6f4", line))
    rows.append((80, 372, 24, False, "#9fb3ab", wrap(summary, 62, 1)[0]))
    for i, (n, label) in enumerate(stats):
        x = (80, 470, 830)[i]
        rows.append((x, 486, 44, True, "#00ff88", n))
        rows.append((x, 522, 19, False, "#8fa79f", label))
    rows.append((80, 580, 21, False, "#7d928b", "Dmitrii Vasilev · admin@t27.ai"))
    return rows


def write_svg(path: Path, rows: list, label: str):
    esc = lambda s: (s.replace("&", "&amp;").replace("<", "&lt;")
                      .replace(">", "&gt;").replace('"', "&quot;"))
    body = "".join(
        f'\n  <text x="{x}" y="{y}" font-family="Inter,DejaVu Sans,Helvetica,Arial,sans-serif"'
        f' font-size="{s}"{" font-weight=\"700\"" if b else ""} fill="{c}"'
        f'{" letter-spacing=\"6\"" if t == "T27.AI · BLOG" else ""}>{esc(t)}</text>'
        for x, y, s, b, c, t in rows)
    path.write_text(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}"'
        f' viewBox="0 0 {W} {H}" role="img" aria-label="{esc(label)}">\n'
        '  <defs>\n'
        '    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">\n'
        '      <stop offset="0%" stop-color="#05070a"/><stop offset="100%" stop-color="#0b1418"/>\n'
        '    </linearGradient>\n'
        '    <linearGradient id="glow" x1="0" y1="0" x2="1" y2="0">\n'
        '      <stop offset="0%" stop-color="#00ff88" stop-opacity="0.9"/>'
        '<stop offset="100%" stop-color="#00ff88" stop-opacity="0.1"/>\n'
        '    </linearGradient>\n'
        '  </defs>\n'
        f'  <rect width="{W}" height="{H}" fill="url(#bg)"/>\n'
        f'  <rect x="0" y="0" width="{W}" height="5" fill="url(#glow)"/>'
        f'{body}\n'
        f'  <line x1="80" y1="412" x2="1120" y2="412" stroke="#1d2b2a" stroke-width="2"/>\n'
        '</svg>\n', encoding="utf-8")


def write_png(path: Path, rows: list):
    from PIL import Image, ImageDraw, ImageFont
    img = Image.new("RGB", (W, H), "#05070a")
    d = ImageDraw.Draw(img)
    for y in range(H):  # the SVG's diagonal gradient, flattened to vertical
        k = y / H
        d.line([(0, y), (W, y)], fill=(int(5 + 6 * k), int(7 + 13 * k), int(10 + 14 * k)))
    for x in range(W):
        a = 0.9 - 0.8 * x / W
        d.line([(x, 0), (x, 4)], fill=(int(5 + a * (0 - 5)), int(7 + a * (255 - 7)),
                                       int(10 + a * (136 - 10))))
    d.line([(80, 412), (1120, 412)], fill="#1d2b2a", width=2)
    for x, y, size, bold, colour, text in rows:
        f = ImageFont.truetype(font_path(bold), size)
        if text == "T27.AI · BLOG":  # letter-spacing 6, drawn glyph by glyph
            cx = x
            for ch in text:
                d.text((cx, y), ch, font=f, fill=colour, anchor="ls")
                cx += d.textlength(ch, font=f) + 6
        else:
            d.text((x, y), text, font=f, fill=colour, anchor="ls")
    img.save(path, "PNG", optimize=True)


def cards(posts: list) -> int:
    made = 0
    for p in posts:
        for lang in ("en", "ru"):
            if lang == "ru" and not p.get("ru"):
                continue
            stem = f"og-blog-{p['slug']}" + ("-ru" if lang == "ru" else "")
            png = REPO / f"{stem}.png"
            if png.is_file():
                continue
            rows = card_layout(p, lang)
            write_svg(REPO / f"{stem}.svg", rows,
                      (p.get("ru", {}).get("title") if lang == "ru" else None) or p["title"])
            write_png(png, rows)
            print(f"drew {stem}.svg + .png")
            made += 1
    return made


def main():
    site = Path(sys.argv[1] if len(sys.argv) > 1 else ".src/apps/website").resolve()
    if not (site / "src/data/blog/posts.ts").is_file():
        raise SystemExit(f"regen-blog: no posts.ts under {site}")
    posts = extract(site)

    before = json.loads(DATA.read_text(encoding="utf-8")) if DATA.is_file() else []
    old = {p["slug"] for p in before}
    new = [p["slug"] for p in posts if p["slug"] not in old]
    gone = sorted(old - {p["slug"] for p in posts})
    DATA.write_text(json.dumps(posts, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"blog-posts.json: {len(posts)} posts"
          + (f", new: {' '.join(new)}" if new else "")
          + (f", withdrawn: {' '.join(gone)}" if gone else ""))

    # A post removed upstream must lose its static directory too, or the drift
    # gate fails the other way round: blog/ holding more than the app ships.
    for slug in gone:
        for root in ("blog", "ru/blog"):
            shutil.rmtree(REPO / root / slug, ignore_errors=True)
        print(f"removed {slug}/ (no longer published upstream)")

    cards(posts)
    print(run(["python3", "build-blog.py"], cwd=REPO).strip().splitlines()[-1])
    run(["python3", "build-landing.py"], cwd=REPO)
    print("sitemap.xml rewritten from what is on disk")


if __name__ == "__main__":
    os.chdir(REPO)
    main()
