#!/usr/bin/env python3
"""Regenerate the static blog from trinity's own posts.ts, unattended.

The chain that publishes a blog post had a manual link in the middle. `blog/` is
generated by build-blog.py from `blog-posts.json`, and `blog-posts.json` was a
snapshot somebody refreshed by hand. verify-site.sh compares the slugs in the
shipped `Blog-*.js` chunk against `ls -d blog/*/` and fails on drift — correctly,
because a post the app lists and the static tree lacks is a 404 for every reader
who does not run JavaScript.

The consequence was that adding a post blocked its own publication, and with it
everything merged afterwards: from 2026-08-13 15:xx UTC to 2026-08-14, twelve
consecutive publisher runs failed on that gate and six unrelated merged pull
requests never reached a reader. The gate was right; nothing was wired to
satisfy it.

So this script owns the whole chain and the publisher calls it on every run:

    posts.ts  ->  blog-posts.json  ->  blog/ + ru/blog/ + feed.xml
                                   ->  og-blog-<slug>.svg/.png for new posts
                                   ->  sitemap.xml (build-landing.py)

Two deliberate choices:

* `publishedPosts` is a function, not an array. `JSON.stringify` on the binding
  itself returns `undefined` and writes a syntactically valid, entirely empty
  file without erroring — which would delete the blog rather than fail. Hence
  the call, and hence the assertions on the parsed result before anything is
  overwritten.

* OG-карточка строится из одной таблицы разметки, а не двумя рендерами. Раньше
  SVG писались вручную, а PNG растрировались на Mac через qlmanage, которого на
  раннере нет. Вторая независимая ветка PNG разошлась бы с SVG при первом же
  изменении, поэтому разметка живёт в `card_layout()`, и оба вывода получают её
  оттуда. Pillow использует добавленный в репозиторий вариативный Inter, а
  `build-og.py` растрирует все SVG тем же семейством на Linux.

Usage: python3 regen-blog.py [path-to-trinity/apps/website]
"""
import json
import math
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent
DATA = REPO / "blog-posts.json"
W, H = 1200, 630

INTER = REPO / "fonts" / "Inter-Variable.ttf"


TITLE_VARIATION = "Black"       # вес 900 — тот же, что в SVG заголовка карточки


def font(size: int, bold=True):
    """Открыть закреплённый в репозитории Inter с нужной вариацией.

    `bold` принимает и имя вариации строкой. Важно измерять ширину тем же
    весом, которым строка будет нарисована: Black шире Bold, и подбор
    кегля по метрикам Bold пустил бы заголовок за поля.
    """
    from PIL import ImageFont
    if not INTER.is_file():
        raise SystemExit("regen-blog: fonts/Inter-Variable.ttf отсутствует — нельзя менять шрифт молча")
    value = ImageFont.truetype(str(INTER), size)
    name = bold if isinstance(bold, str) else ("Bold" if bold else "Regular")
    value.set_variation_by_name(name)
    return value


def run(cmd, cwd=None):
    r = subprocess.run(cmd, cwd=cwd, text=True, capture_output=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit(f"regen-blog: {' '.join(cmd[:3])} failed ({r.returncode})")
    return r.stdout


def extract(site: Path) -> list:
    """posts.ts -> parsed list, by transpiling the real module."""
    esbuild = site / "node_modules/.bin/esbuild"
    exe = [str(esbuild)] if esbuild.is_file() else ["npx", "--yes", "esbuild"]
    mjs = Path("/tmp/regen-posts.mjs")
    run(exe + ["src/data/blog/posts.ts", "--format=esm", "--platform=node",
               f"--outfile={mjs}", "--log-level=error"], cwd=site)
    out = run(["node", "-e",
               f"import('{mjs}').then(m=>"
               "process.stdout.write(JSON.stringify(m.publishedPosts(),null,1)))"])
    posts = json.loads(out)
    # Empty or malformed here would silently erase the blog on the next step,
    # which is a worse failure than not publishing.
    if not isinstance(posts, list) or len(posts) < 1:
        raise SystemExit(f"regen-blog: publishedPosts() gave {type(posts).__name__} "
                         f"of length {len(posts) if hasattr(posts,'__len__') else '?'}")
    for p in posts:
        for k in ("slug", "title", "summary", "date", "body"):
            if not p.get(k):
                raise SystemExit(f"regen-blog: post {p.get('slug','?')} has no {k}")
    return posts


def wrap(text: str, width: int, lines: int) -> list:
    words, out, cur = text.split(), [], ""
    for w in words:
        cand = f"{cur} {w}".strip()
        if len(cand) <= width or not cur:
            cur = cand
        else:
            out.append(cur)
            cur = w
            if len(out) == lines:
                break
    if cur and len(out) < lines:
        out.append(cur)
    if len(out) == lines and len(" ".join(out)) < len(text):
        out[-1] = out[-1].rstrip(" .,;:") + "…"
    return out


def fit_title(title: str, lang: str) -> tuple:
    """Подобрать самый крупный кегль, при котором заголовок влезает в три строки.

    Карточку читают в ленте, где 1200px сжаты примерно до 500: кегль 46
    превращался в 19 и заголовок пропадал. Ширина считается метриками Inter, а
    не числом символов, иначе строка из широких букв вылезает за поля.
    """
    from PIL import ImageDraw, Image
    draw = ImageDraw.Draw(Image.new("RGB", (10, 10)))
    limit = 1010
    for size in (96, 84, 74, 64, 56):
        f = font(size, TITLE_VARIATION)
        words, lines, cur = title.split(), [], ""
        for w in words:
            cand = f"{cur} {w}".strip()
            if draw.textlength(cand, font=f) <= limit or not cur:
                cur = cand
            else:
                lines.append(cur)
                cur = w
        if cur:
            lines.append(cur)
        if len(lines) <= 3 and all(draw.textlength(l, font=f) <= limit for l in lines):
            return size, lines
    # Ничего не подошло: обрезать по последней строке, но не молча — многоточие
    # показывает читателю, что заголовок продолжается в статье.
    size = 56
    f = font(size, TITLE_VARIATION)
    words, lines, cur = title.split(), [], ""
    for w in words:
        cand = f"{cur} {w}".strip()
        if draw.textlength(cand, font=f) <= limit or not cur:
            cur = cand
        else:
            lines.append(cur)
            cur = w
            if len(lines) == 3:
                break
    if cur and len(lines) < 3:
        lines.append(cur)
    lines[-1] = lines[-1].rstrip(" .,;:") + "\u2026"
    return size, lines


PHI = 1.618033988749895
GOLDEN_ANGLE = 2 * math.pi / (PHI * PHI)   # 137,5077° — окружность, поделённая на φ²


def starfield() -> str:
    """То же звёздное поле, что на главной, но застывшее в одном кадре.

    Параметры взяты из `components/PhiStarfield.tsx` без пересчёта:
    спираль Фогеля (угол i·137,5077°, радиус √(i/N)), 233 звезды, сжатие по
    вертикали 0,92, радиус 0,5+1,5·(1−d), базовая прозрачность 0,28+0,5·(1−d).
    Мерцание в картинке невозможно, поэтому взята фаза покоя того же
    выражения (0,62+0,38·sin(phase)) — так яркости распределены как в живом
    кадре, а не ровным слоем.

    Звёзды под заголовком гасятся втрое: в ленте картинка показывается
    шириной около 500 px, и точка вплотную к букве там читается как дефект
    растра, а не как звезда.
    """
    cx, cy = W / 2, H / 2
    max_r = math.hypot(W, H) * 0.62
    out = []
    for i in range(233):
        t = (i + 0.5) / 233
        r = math.sqrt(t) * max_r
        a = i * GOLDEN_ANGLE
        x = cx + math.cos(a) * r
        y = cy + math.sin(a) * r * 0.92
        if not (-6 <= x <= W + 6 and -6 <= y <= H + 6):
            continue
        rad = 0.5 + (1 - t) * 1.5
        phase = (i * GOLDEN_ANGLE) % (2 * math.pi)
        alpha = (0.28 + (1 - t) * 0.5) * (0.62 + 0.38 * math.sin(phase))
        if 60 <= x <= 1120:
            if 140 <= y <= 500:            # полоса заголовка
                alpha *= 0.34
            elif 90 <= y <= 132 or 536 <= y <= 596:
                # Строки мелкого кегля: там звезда попадает в букву и читается
                # как лишняя точка над буквой, а не как фон.
                alpha *= 0.12
        out.append(f'  <circle cx="{x:.1f}" cy="{y:.1f}" r="{rad:.2f}"'
                   f' fill="#ffffff" opacity="{alpha:.3f}"/>\n')
    return "".join(out)


def card_svg(post: dict, lang: str) -> str:
    """Одна карточка: крупный заголовок, тонкая подпись, ничего лишнего.

    Резюме поста с карточки убрано намеренно. В ленте под картинкой уже стоит
    og:description тем же текстом, поэтому вторая копия отнимала место у
    единственного элемента, который читается на бегу, — заголовка.
    """
    esc = lambda s: (str(s).replace("&", "&amp;").replace("<", "&lt;")
                     .replace(">", "&gt;").replace('"', "&quot;"))
    t = post.get("ru", {}) if lang == "ru" else post
    title = t.get("title") or post["title"]
    minutes = post.get("readingMinutes") or "\u2014"
    receipts, questions = len(post.get("receipts") or []), len(post.get("openQuestions") or [])
    facts = (f"{minutes} \u043c\u0438\u043d \u0447\u0442\u0435\u043d\u0438\u044f  \u00b7  {receipts} \u043f\u0440\u0443\u0444\u043e\u0432 \u0441\u043e \u0441\u0441\u044b\u043b\u043a\u043e\u0439  \u00b7  {questions} \u043e\u0442\u043a\u0440\u044b\u0442\u044b\u0445 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u0432"
             if lang == "ru" else
             f"{minutes} minute read  \u00b7  {receipts} linked receipts  \u00b7  {questions} open questions")
    kicker = "T27.AI \u00b7 \u0411\u041b\u041e\u0413" if lang == "ru" else "T27.AI \u00b7 BLOG"
    size, lines = fit_title(title, lang)
    lead = round(size * 1.1)
    last = 466                      # нижняя базовая линия блока заголовка
    first = last - (len(lines) - 1) * lead
    ff = "Inter,DejaVu Sans,Helvetica,Arial,sans-serif"
    # Столбик троичных знаков стоит в правой полосе x>1090, куда заголовок не
    # заходит по построению (его предел ширины 1010 от x=80). Знак во всю
    # карточку, стоявший тут раньше, пересекался с третьей строкой заголовка.
    motif = "".join(
        f'  <text x="1112" y="{y}" font-family="{ff}" font-size="86" font-weight="700"'
        f' fill="#00ff88" opacity="0.13">{g}</text>\n'
        for g, y in (("\u2212", 250), ("0", 350), ("+", 450)))
    body = "".join(
        f'\n  <text x="80" y="{first + i * lead}" font-family="{ff}" font-size="{size}"'
        f' font-weight="900" fill="#ffffff">{esc(line)}</text>'
        for i, line in enumerate(lines))
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}"'
        f' viewBox="0 0 {W} {H}" role="img" aria-label="{esc(title)}">\n'
        f'  <rect width="{W}" height="{H}" fill="#000000"/>\n'
        f'{starfield()}'
        f'{motif}'
        f'  <rect x="0" y="0" width="{W}" height="4" fill="#00ff88"/>\n'
        '  <rect x="80" y="106" width="12" height="12" fill="#00ff88"/>\n'
        f'  <text x="108" y="120" font-family="{ff}" font-size="21" letter-spacing="6"'
        f' fill="#00ff88">{esc(kicker)}</text>'
        f'{body}\n'
        '  <line x1="80" y1="524" x2="1120" y2="524" stroke="#18292b" stroke-width="2"/>\n'
        f'  <text x="80" y="574" font-family="{ff}" font-size="23" fill="#93aaa2">{esc(facts)}</text>\n'
        f'  <text x="1120" y="574" text-anchor="end" font-family="{ff}" font-size="21"'
        '  fill="#6f8580">Dmitrii Vasilev \u00b7 t27.ai</text>\n'
        '</svg>\n')


def render_png(svg: Path, png: Path) -> None:
    """Растр карточки — это ровно её SVG, а не вторая рисовалка.

    Пока PNG рисовался отдельным кодом на Pillow, любая правка макета
    расходилась с исходником, и в ленту уходила версия, которой в репозитории
    не было. rsvg-convert со шрифтом из репозитория снимает этот класс ошибок.
    """
    import tempfile
    if not shutil.which("rsvg-convert"):
        raise SystemExit("regen-blog: нет rsvg-convert (librsvg2-bin) — карточку нечем растрировать")
    with tempfile.TemporaryDirectory(prefix="t27-card-") as tmp_name:
        tmp = Path(tmp_name)
        conf = tmp / "fonts.conf"
        conf.write_text(
            '<?xml version="1.0"?>\n'
            '<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">\n'
            f'<fontconfig><dir>{REPO / "fonts"}</dir>'
            f'<cachedir>{tmp / "cache"}</cachedir>'
            '<alias><family>Inter</family><default><family>Inter</family></default></alias>'
            '</fontconfig>\n', encoding="utf-8")
        env = os.environ.copy()
        env["FONTCONFIG_FILE"], env["FONTCONFIG_PATH"] = str(conf), str(tmp)
        r = subprocess.run(["rsvg-convert", "--width", str(W), "--height", str(H),
                            "--output", str(png), str(svg)],
                           text=True, capture_output=True, env=env)
        if r.returncode:
            raise SystemExit(f"regen-blog: rsvg-convert {svg.name}: {r.stderr.strip()}")


def cards(posts: list) -> int:
    made = 0
    for p in posts:
        for lang in ("en", "ru"):
            if lang == "ru" and not p.get("ru"):
                continue
            stem = f"og-blog-{p['slug']}" + ("-ru" if lang == "ru" else "")
            svg = REPO / f"{stem}.svg"
            svg.write_text(card_svg(p, lang), encoding="utf-8")
            render_png(svg, REPO / f"{stem}.png")
            print(f"drew {stem}.svg + .png")
            made += 1
    return made


def main():
    site = Path(sys.argv[1] if len(sys.argv) > 1 else ".src/apps/website").resolve()
    if not (site / "src/data/blog/posts.ts").is_file():
        raise SystemExit(f"regen-blog: no posts.ts under {site}")
    posts = extract(site)

    before = json.loads(DATA.read_text(encoding="utf-8")) if DATA.is_file() else []
    old = {p["slug"] for p in before}
    new = [p["slug"] for p in posts if p["slug"] not in old]
    gone = sorted(old - {p["slug"] for p in posts})
    DATA.write_text(json.dumps(posts, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"blog-posts.json: {len(posts)} posts"
          + (f", new: {' '.join(new)}" if new else "")
          + (f", withdrawn: {' '.join(gone)}" if gone else ""))

    # A post removed upstream must lose its static directory too, or the drift
    # gate fails the other way round: blog/ holding more than the app ships.
    for slug in gone:
        for root in ("blog", "ru/blog"):
            shutil.rmtree(REPO / root / slug, ignore_errors=True)
        print(f"removed {slug}/ (no longer published upstream)")

    cards(posts)
    print(run(["python3", "build-blog.py"], cwd=REPO).strip().splitlines()[-1])
    run(["python3", "build-landing.py"], cwd=REPO)
    print("sitemap.xml rewritten from what is on disk")


if __name__ == "__main__":
    os.chdir(REPO)
    main()
